require: rubocop-rails

Rails:
  Enabled: true

Rails/LinkToBlank:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

AllCops:
  TargetRubyVersion: 3.0.1
  TargetRailsVersion: 6.1.3.1
  NewCops: enable
  
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/*'

Layout/LineLength:
  Max: 120

  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

  Exclude:
    - 'config/application.rb'

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/TrailingEmptyLines:
  Enabled: false
