version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:5
    ports:
      - 6379:6379
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    ports: ['4444:4444', '5900:5900']
    logging:
      driver: none

volumes:
  bundle_cache: 
  db_data:
