default: &default
  adapter: redis
  url: 'redis://redis:6379/1'
  
development:
  <<: *default
  channel_prefix: app_development

test:
  <<: *default
  channel_prefix: app_test

production:
  <<: *default
  channel_prefix: app_production
